"""BB-SUITE Central Security Package."""
from backend.security.config import (
    BB_ADMIN_PASSWORD,
    BB_ADMIN_USERNAME,
    BB_ALLOW_INSECURE_TLS,
    BB_ALLOW_PRIVATE_TARGETS,
    BB_CORS_ORIGINS,
    BB_ENV,
    BB_HOST,
    BB_MAX_REDIRECTS,
    BB_MAX_RESPONSE_SIZE,
    BB_PORT,
    BB_SECRET_KEY,
    BB_TIMEOUT_CONNECT,
    BB_TIMEOUT_READ,
    BB_TIMEOUT_TOTAL,
    is_private_allowed,
)
from backend.security.confidence import (
    Confidence,
    Severity,
    create_finding,
    standard_response,
)
from backend.security.http_client import (
    SafeResponse,
    safe_get,
    safe_head,
    safe_post,
    safe_request,
)
from backend.security.logger import audit_logger, log_security_event, redact_secrets
from backend.security.target_validator import (
    TargetValidationError,
    validate_hostname,
    validate_redirect_target,
    validate_target_url,
)

__all__ = [
    "BB_ENV",
    "BB_HOST",
    "BB_PORT",
    "BB_ALLOW_PRIVATE_TARGETS",
    "BB_ALLOW_INSECURE_TLS",
    "BB_MAX_RESPONSE_SIZE",
    "BB_MAX_REDIRECTS",
    "BB_TIMEOUT_CONNECT",
    "BB_TIMEOUT_READ",
    "BB_TIMEOUT_TOTAL",
    "BB_ADMIN_USERNAME",
    "BB_ADMIN_PASSWORD",
    "BB_SECRET_KEY",
    "BB_CORS_ORIGINS",
    "is_private_allowed",
    "Confidence",
    "Severity",
    "create_finding",
    "standard_response",
    "TargetValidationError",
    "validate_hostname",
    "validate_target_url",
    "validate_redirect_target",
    "SafeResponse",
    "safe_request",
    "safe_get",
    "safe_post",
    "safe_head",
    "audit_logger",
    "log_security_event",
    "redact_secrets",
]
